GET http://localhost:5086/games

###
GET http://localhost:5086/games/1

###
POST http://localhost:5086/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

###
PUT http://localhost:5086/games/2
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1991-01-05"
}

###
DELETE http://localhost:5086/games/4